# Generated by Django 4.2.18 on 2025-01-31 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='average_rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='content',
            name='rating_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='content',
            name='rating_distribution',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='rating',
            name='processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='content',
            index=models.Index(fields=['rating_count'], name='contents_co_rating__8193a4_idx'),
        ),
        migrations.AddIndex(
            model_name='content',
            index=models.Index(fields=['average_rating'], name='contents_co_average_e560cb_idx'),
        ),
    ]
