version: '3.8'

services:
  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
  web:
    build: .
    command: >
      sh -c "python manage.py makemigrations contents &&
             python manage.py migrate &&
             python manage.py populate_db &&
             python manage.py collectstatic --noinput &&
             gunicorn --bind 0.0.0.0:8000 content_rating.wsgi:application"
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
    depends_on:
      - redis
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - REDIS_URL=redis://redis:6379/1
      - DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1


volumes:
  static_volume:
  media_volume:
  redis_data: