services:
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=contents_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
  web:
    build: .
    command: >
      sh -c "python manage.py makemigrations contents &&
             python manage.py migrate &&
             python manage.py populate_db &&
             python manage.py collectstatic --noinput &&
             gunicorn --bind 0.0.0.0:8000 content_rating.wsgi:application"
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - REDIS_URL=redis://redis:6379/1
      - DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1
      - DATBASE_URL=postgres
      - POSTGRES_DB=contents_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres


volumes:
  postgres_data:
  static_volume:
  media_volume:
  redis_data: